---
swagger: 2.0
info:
  description: This is a demo
  version: 1.0.0
  title: DELILAH PROJECT
  contact:
    email: delilah@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /delilah/1.0.0
tags:
- name: admin
  description: Secured Admin-only calls
- name: client
  description: Operations available to regular developers
schemes:
- https
paths:
  /orders:
    get:
      summary: lista los pedidos
      parameters:
        - in: path
          type: integer
          name: id
          description: order Id
          required: true
    post:
      summary: confirma un nuevo pedido
  /orders/{id}:
    put: 
      summary: actualiza el estado de un pedido
    get:
      summary: muestra información de un pedido
      parameters:
        - in: path
          type: integer
          name: id
          description: order Id
          required: true
    delete:
      summary: cancela una orden 
  /productos:
    get:
      summary: lista los productos
    post:
      summary: agrega un nuevo producto disponble para la venta
  /productos/{id}:
    delete:
      summary: quita un producto de la venta
    put:
      summary: actualiza precios del producto 
      parameters:
        - in: path
          type: integer
          name: id
          description: product Id
          required: true
  /usuarios:
    get:
      summary: lista los usuarios
      produces:
      - application/json
    post:
      summary: agrega un nuevo usuario
      parameters:
        - in: body
          name: body
          description: Update an user
          required: true
      responses:
        '200':
          description: successful operation
        '404':
          description: Not Found
        '500':
          description: Internal server error
  /usuarios/{id}:
    get:
      summary: expone los datos de un usuario
    put:
      summary: actualiza los datos de un usuario
      parameters:
          - in: path
            type: integer
            name: id
            description: User Id
            required: true
          - in: body
            name: body
            description: Update an user
            required: true
      responses:
        '200':
          description: successful operation
        '404':
          description: Not Found
        '500':
          description: Internal server error
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'